api:
	build:
		context: ./
	container_name: local_development_api
	volumes:
		- ../../:/api
	ports:
		- 3000:3000
	depends_on:
		- mongo
		- redis
	links:
		- mongo
		- redis

mongo:
	image: mongo
	ports:
		- 27017:27017

redis:
	image: redis
	ports:
		- 6379:6379
